import Head from "next/head";
import { ArrowSmallRightIcon } from "@heroicons/react/24/solid";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mushare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center overscroll-none bg-zinc-900">
        <div className="container flex w-2/3 max-w-xl flex-col items-center justify-between gap-3 px-4 py-16">
          <h1 className="text-3xl font-bold text-zinc-400">Mushare</h1>
          <h3 className="text-zinc-400">
            Share Music to Friends on Different Streaming Platform with One Link
          </h3>
          <div className="flex h-12 w-full justify-between rounded-lg bg-zinc-600 ">
            <input
              className="w-full rounded-xl bg-zinc-600 p-2 text-zinc-400 focus:outline-none"
              placeholder="Enter Link of Music"
            />
            <button className="flex h-full w-20 items-center justify-center">
              <ArrowSmallRightIcon className="h-6 w-6 text-zinc-200" />
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
