import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import PulseLoader from "react-spinners/PulseLoader";

export default function Song() {
  const { query } = useRouter();
  const { isLoading, data } = api.songs.getById.useQuery(
    typeof query.id === "string" ? query.id : "",
  );
  return (
    <>
      <Head>
        <title>{data ? `${data.title} | ` : ""} Mushare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center overscroll-none bg-zinc-900 text-zinc-300">
        {isLoading && <PulseLoader color={"#a1a1aa"} />}
        {!isLoading &&
          (data ? (
            <div className="flex flex-col items-center justify-center">
              <div className="text-3xl">{data.title}</div>
              <div className="text-xl">
                {data.artists
                  .map((artist) => `${artist.name}, `)
                  .toString()
                  .slice(0, -2)}
              </div>
            </div>
          ) : (
            <div className="text-4xl">
              {"The page you're looking for doesn't exists"}
            </div>
          ))}
      </main>
    </>
  );
}
