import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import PulseLoader from "react-spinners/PulseLoader";
import Link from "next/link";

export default function Song() {
  const { query } = useRouter();
  const { isLoading, data } = api.songs.getById.useQuery(
    typeof query.id === "string" ? query.id : "",
  );
  return (
    <>
      <Head>
        <title>{data ? `${data.title} | ` : ""} Mushare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center overscroll-none bg-zinc-900 text-zinc-300">
        {isLoading && <PulseLoader color={"#a1a1aa"} />}
        {!isLoading &&
          (data ? (
            <div className="flex w-full flex-col items-center justify-center gap-2">
              <div className="text-3xl">{data.title}</div>
              <div className="text-xl">{data.artists}</div>
              {data.spotify && (
                <Link
                  className="flex w-1/4 justify-center rounded-xl bg-zinc-600 p-2 text-center text-zinc-300"
                  href={`https://open.spotify.com/track/${data.spotify}`}
                >
                  Listen on Spotify
                </Link>
              )}
            </div>
          ) : (
            <div className="text-4xl">
              {"The page you're looking for doesn't exists"}
            </div>
          ))}
      </main>
    </>
  );
}
